services:
  watcher:
    build:
      target: production
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Denver
      - AIRCRAFT_INFO_DB=/home/node/app/data/aircraft_info.db
    volumes:
      - aircraft_db:/home/node/app/data

volumes:
  aircraft_db: