name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --tag watcher-in-the-sky:$(date +%s)
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
